### ISSUE TITLE
Difference to websocketd

### ISSUE THREAD

**Issue by juliangaal** [benas/ssed#1]
Hi,
you mentioned, your project is inspired by websocketd. What was the reason you wrote your own solution? What's the difference, except being able to use the pipe operator and the obviously much smaller code base?

Just a thing that caught my eye: you can make GitHub ignore release.sh for it's language statistics ;) it is a go project first, after all. See [here](https://stackoverflow.com/questions/19052834/is-it-possible-to-exclude-files-from-git-language-statistics)

**Comment by fmbenhassine** [comment]
> What was the reason you wrote your own solution? What's the difference, except being able to use the pipe operator and the obviously much smaller code base?

A couple of reasons:

* websocketd is bi-directionel which means you can pipe to it anything coming from the internet. This is opening the door to all kinds of attacks and is definitely a security hole (See [this](https://news.ycombinator.com/item?id=6879667) interesting hackernews thread about this point). Gossed is on the other side uni-directionel, it only pushes data to browsers.

* When I first used websocketd, it was written in node js and the installation process was not as easy as grabbing a binary. That's why I decided to use golang for Gossed. But now websocketd has been re-written in golang too.

Does this make sense?

> Just a thing that caught my eye: you can make GitHub ignore release.sh for it's language statistics ;) it is a go project first, after all. See here

Thanks for the hint!

**Comment by fmbenhassine** [comment]
Closing this as I believe I answered your questions.

> Just a thing that caught my eye: you can make GitHub ignore release.sh for it's language statistics ;) it is a go project first, after all. See here

Done in 28cb04fd3b659f1347cf5cb41cd0174a935a56f5. Thank you for the hint!
